[package]
name = "videnoa-controller"
version.workspace = true
rust-version.workspace = true
edition = "2021"
build = "build.rs"

[[bin]]
name = "videnoa-controller"
path = "src/main.rs"

[dependencies]
axum.workspace = true
chrono.workspace = true
clap.workspace = true
figment.workspace = true
mime_guess.workspace = true
percent-encoding.workspace = true
rust-embed.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
thiserror = "2"
tokio.workspace = true
url.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile = "3"
tower.workspace = true

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
