[package]
name = "videnoa-controller"
version.workspace = true
rust-version.workspace = true
edition = "2021"
build = "build.rs"

[[bin]]
name = "videnoa-controller"
path = "src/main.rs"

[dependencies]
argon2.workspace = true
axum.workspace = true
base64.workspace = true
cap-fs-ext.workspace = true
cap-std.workspace = true
chrono.workspace = true
clap.workspace = true
figment.workspace = true
mime_guess.workspace = true
percent-encoding.workspace = true
rand_core.workspace = true
rust-embed.workspace = true
rpassword.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
sqlx.workspace = true
subtle.workspace = true
thiserror = "2"
tokio.workspace = true
url.workspace = true
uuid.workspace = true

[dev-dependencies]
futures-util.workspace = true
hyper = { version = "1", features = ["http1", "server"] }
hyper-util = { version = "0.1", features = ["tokio"] }
reqwest.workspace = true
tempfile = "3"
tower.workspace = true

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
