import { mkdir, writeFile } from "node:fs/promises"

import { expect, test } from "@playwright/test"

import { installOperationalApi } from "./operations-fixtures"

const evidenceDir = "../.omo/evidence/videnoa-controller/task-18/workers-settings"

test("operates workers and runtime settings with safe failures", async ({ page }) => {
  // Given: deterministic same-origin Task 18 API fixtures.
  await mkdir(evidenceDir, { recursive: true })
  const api = await installOperationalApi(page)
  await page.setViewportSize({ width: 1280, height: 900 })

  // When: the operator manages durable worker capacity.
  await page.goto("/workers")
  await expect(page.getByRole("heading", { name: "Workers" })).toBeVisible()
  await expect(page.getByText("health probe timed out")).toBeVisible()
  const workerTableFrame = page.getByRole("region", { name: "Scrollable worker results" })
  await workerTableFrame.focus()
  await expect(workerTableFrame).toBeFocused()
  await page.screenshot({ path: `${evidenceDir}/workers-desktop-scroll-focus.png`, fullPage: false })
  await page.getByRole("button", { name: "Add Worker" }).click()
  await page.getByLabel("Worker name").fill("render-west")
  await page.getByLabel("Worker API URL").fill("https://worker-west.test:3443?secret=blocked")
  await page.getByRole("button", { name: "Save Worker" }).click()
  await expect(page.getByText("Enter a credential-free HTTP(S) base URL without a query or fragment.")).toBeVisible()
  await expect(page.getByLabel("Worker API URL")).toBeFocused()
  await expect(page.getByLabel("Worker API URL")).toHaveAttribute("aria-describedby", "worker-api-url-error")
  await page.screenshot({ path: `${evidenceDir}/workers-desktop-validation.png`, fullPage: true })
  await page.getByLabel("Worker API URL").fill("https://worker-west.test:3443")
  await page.getByLabel("Compute slots").fill("65536")
  expect(await page.getByLabel("Compute slots").evaluate((input: HTMLInputElement) => input.validity.valid)).toBe(false)
  await page.getByRole("button", { name: "Save Worker" }).click()
  await expect(page.getByLabel("Compute slots")).toBeFocused()
  await expect(page.getByLabel("Compute slots")).toHaveAttribute("aria-describedby", "worker-slots-error")
  await page.getByLabel("Compute slots").fill("8")
  await page.getByRole("button", { name: "Save Worker" }).click()
  await expect(page.getByText("render-west")).toBeVisible()
  await page.getByRole("button", { name: "Add Worker" }).click()
  await page.getByLabel("Worker name").fill("render-east")
  await page.getByLabel("Worker API URL").fill("http://worker-north.test:3000")
  await page.getByRole("button", { name: "Save Worker" }).click()
  await expect(page.getByLabel("Worker name").locator("xpath=following-sibling::small")).toHaveText("Enter a unique worker name.")
  await expect(page.getByLabel("Worker name")).toBeFocused()
  await page.getByLabel("Worker name").fill("render-north")
  await page.getByLabel("Worker API URL").fill("http://worker-east.test:3000")
  await page.getByRole("button", { name: "Save Worker" }).click()
  await expect(page.getByText("Enter a unique worker API URL.")).toBeVisible()
  await expect(page.getByLabel("Worker API URL")).toBeFocused()
  await page.getByRole("button", { name: "Close worker form" }).click()
  await page.getByRole("button", { name: "Edit render-east" }).click()
  const readsBeforeCapacityConflict = api.journal.filter((entry) => entry === "workers:get").length
  await page.getByLabel("Compute slots").fill("1")
  await page.getByRole("button", { name: "Save Worker" }).click()
  await expect(page.getByRole("alert")).toContainText("currently used durable capacity")
  await expect.poll(() => api.journal.filter((entry) => entry === "workers:get").length).toBe(readsBeforeCapacityConflict + 1)
  const readsBeforeStaleWorker = api.journal.filter((entry) => entry === "workers:get").length
  api.staleNextWorkerUpdate()
  await page.getByLabel("Compute slots").fill("6")
  await page.getByRole("button", { name: "Save Worker" }).click()
  await expect(page.getByRole("alert")).toContainText("current row was reloaded")
  await expect.poll(() => api.journal.filter((entry) => entry === "workers:get").length).toBe(readsBeforeStaleWorker + 1)
  await page.getByRole("button", { name: "Save Worker" }).click()
  await expect(page.getByText("2 / 6")).toBeVisible()
  await page.getByRole("button", { name: "Disable render-east" }).click()
  await expect(page.getByRole("button", { name: "Enable render-east" })).toBeVisible()
  const deleteWorker = page.getByRole("button", { name: "Delete render-east" })
  await deleteWorker.click()
  const confirmation = page.getByRole("alertdialog", { name: "Delete render-east?" })
  await expect(confirmation).toBeVisible()
  await expect(confirmation.getByRole("button", { name: "Keep Worker" })).toBeFocused()
  await page.keyboard.press("Shift+Tab")
  await expect(confirmation.getByRole("button", { name: "Delete Worker" })).toBeFocused()
  await page.keyboard.press("Tab")
  await expect(confirmation.getByRole("button", { name: "Keep Worker" })).toBeFocused()
  await page.screenshot({ path: `${evidenceDir}/workers-desktop-delete-confirmation.png`, fullPage: true })
  await page.keyboard.press("Escape")
  await expect(confirmation).toBeHidden()
  await expect(deleteWorker).toBeFocused()
  await deleteWorker.click()
  await confirmation.getByRole("button", { name: "Delete Worker" }).click()
  const deleteAlert = page.getByRole("alert")
  await expect(deleteAlert).toContainText("still referenced by durable tasks")
  await expect(deleteWorker).toBeFocused()
  api.allowNextWorkerDelete()
  const deletableWorker = page.getByRole("button", { name: "Delete render-west" })
  await deletableWorker.click()
  await page.getByRole("alertdialog", { name: "Delete render-west?" }).getByRole("button", { name: "Delete Worker" }).click()
  await expect(deletableWorker).toBeHidden()
  await expect(page.getByRole("button", { name: "Add Worker" })).toBeFocused()
  await page.screenshot({ path: `${evidenceDir}/workers-desktop-delete-success.png`, fullPage: true })
  await page.locator(".worker-table-frame").evaluate((element) => { element.scrollLeft = 0 })
  await page.screenshot({ path: `${evidenceDir}/workers-desktop.png`, fullPage: true })
  await page.locator(".worker-table-frame").evaluate((element) => { element.scrollLeft = element.scrollWidth })
  await page.screenshot({ path: `${evidenceDir}/workers-desktop-actions.png`, fullPage: true })
  await page.setViewportSize({ width: 768, height: 900 })
  await page.locator(".worker-table-frame").evaluate((element) => { element.scrollLeft = 0 })
  await page.screenshot({ path: `${evidenceDir}/workers-tablet.png`, fullPage: true })
  await page.locator(".worker-table-frame").evaluate((element) => { element.scrollLeft = element.scrollWidth })
  await page.screenshot({ path: `${evidenceDir}/workers-tablet-actions.png`, fullPage: true })

  // When: the operator updates live settings and controls scheduler admission.
  await page.setViewportSize({ width: 1280, height: 900 })
  await page.getByRole("link", { name: "Settings" }).click()
  await page.getByLabel("Concurrent uploads").fill("0")
  expect(await page.getByLabel("Concurrent uploads").evaluate((input: HTMLInputElement) => input.validity.valid)).toBe(false)
  await page.getByRole("button", { name: "Save runtime settings" }).click()
  await expect(page.getByLabel("Concurrent uploads")).toBeFocused()
  await expect(page.getByLabel("Concurrent uploads")).toHaveAttribute("aria-describedby", "settings-max_concurrent_uploads-error")
  await page.screenshot({ path: `${evidenceDir}/settings-desktop-validation.png`, fullPage: true })
  await page.getByLabel("Initial retry seconds").fill("31")
  await page.getByLabel("Concurrent uploads").fill("5")
  await page.getByRole("button", { name: "Save runtime settings" }).click()
  await expect(page.getByLabel("Initial retry seconds")).toBeFocused()
  await expect(page.getByLabel("Initial retry seconds")).toHaveAttribute("aria-describedby", "settings-initial_seconds-error")
  await page.getByLabel("Initial retry seconds").fill("2")
  const readsBeforeStaleSettings = api.journal.filter((entry) => entry === "settings:get").length
  api.staleNextSettingsSave()
  await page.getByLabel("Concurrent uploads").fill("5")
  await page.getByRole("button", { name: "Save runtime settings" }).click()
  await expect(page.getByRole("alert")).toContainText("Current values were reloaded")
  await expect.poll(() => api.journal.filter((entry) => entry === "settings:get").length).toBe(readsBeforeStaleSettings + 1)
  await page.getByLabel("Concurrent uploads").fill("5")
  await page.getByRole("button", { name: "Save runtime settings" }).click()
  await expect(page.getByText("Settings version 9")).toBeVisible()
  await page.getByRole("button", { name: "Pause scheduler" }).click()
  await expect(page.getByText("Paused", { exact: true })).toBeVisible()
  await expect(page.getByText("Pause blocks new reservations, prefetch, and compute starts. Already-running processing continues; transfer and publication continue where applicable; cleanup continues.")).toBeVisible()
  await expect(page.getByRole("region", { name: "Scheduler capacity" })).toContainText("reservation, prefetch, compute starts, and transfer concurrency")
  await page.reload()
  await expect(page.getByText("Paused", { exact: true })).toBeVisible()
  await expect(page.getByText("Pause blocks new reservations, prefetch, and compute starts. Already-running processing continues; transfer and publication continue where applicable; cleanup continues.")).toBeVisible()
  await page.getByRole("button", { name: "Resume scheduler" }).click()
  await expect(page.getByText("Running", { exact: true })).toBeVisible()
  await page.evaluate(() => {
    if (document.activeElement instanceof HTMLElement) document.activeElement.blur()
    const main = document.querySelector(".shell-main")
    if (main instanceof HTMLElement) main.scrollTop = 0
  })
  await expect.poll(() => page.locator(".shell-main").evaluate((element) => element.scrollTop)).toBe(0)
  await expect(page.getByRole("heading", { name: "Settings" })).toBeInViewport()
  await page.locator(".operation-header").screenshot({ path: `${evidenceDir}/settings-desktop.png` })
  await page.locator(".settings-editor").screenshot({ path: `${evidenceDir}/settings-desktop-runtime-section.png` })
  await page.getByRole("heading", { name: "Restart-required configuration" }).evaluate((element) => element.scrollIntoView({ block: "start" }))
  await page.screenshot({ path: `${evidenceDir}/settings-desktop-readonly.png` })
  await page.setViewportSize({ width: 768, height: 900 })
  await page.locator(".shell-main").evaluate((element) => { element.scrollTop = 0 })
  await page.screenshot({ path: `${evidenceDir}/settings-tablet.png` })
  await page.getByRole("heading", { name: "Timeouts" }).evaluate((element) => element.scrollIntoView({ block: "start" }))
  await page.screenshot({ path: `${evidenceDir}/settings-tablet-timeouts.png` })
  await page.getByRole("heading", { name: "Retry policy" }).evaluate((element) => element.scrollIntoView({ block: "start" }))
  await page.screenshot({ path: `${evidenceDir}/settings-tablet-retry.png` })
  await page.getByRole("heading", { name: "Restart-required configuration" }).evaluate((element) => element.scrollIntoView({ block: "start" }))
  await page.screenshot({ path: `${evidenceDir}/settings-tablet-readonly.png` })
  await page.locator(".read-only-settings").screenshot({ path: `${evidenceDir}/settings-tablet-readonly-section.png` })

  // Then: the narrow UI does not overflow and mutation versions remain observable.
  await page.setViewportSize({ width: 375, height: 812 })
  await page.locator(".shell-main").evaluate((element) => { element.scrollTop = 0 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)).toBe(false)
  await page.screenshot({ path: `${evidenceDir}/settings-narrow.png` })
  await page.getByRole("heading", { name: "Timeouts" }).evaluate((element) => element.scrollIntoView({ block: "start" }))
  await page.screenshot({ path: `${evidenceDir}/settings-narrow-timeouts.png` })
  await page.getByRole("heading", { name: "Retry policy" }).evaluate((element) => element.scrollIntoView({ block: "start" }))
  await page.screenshot({ path: `${evidenceDir}/settings-narrow-retry.png` })
  await page.getByRole("heading", { name: "Restart-required configuration" }).evaluate((element) => element.scrollIntoView({ block: "start" }))
  await page.screenshot({ path: `${evidenceDir}/settings-narrow-readonly.png` })
  await page.locator(".read-only-settings").screenshot({ path: `${evidenceDir}/settings-narrow-readonly-section.png` })
  await page.getByRole("link", { name: "Workers" }).click()
  await expect(page).toHaveURL(/\/workers$/)
  await expect(page.getByRole("heading", { name: "Workers" })).toBeVisible()
  await page.getByRole("button", { name: "Delete render-east" }).click()
  await expect(page.getByRole("alertdialog", { name: "Delete render-east?" })).toBeVisible()
  await page.screenshot({ path: `${evidenceDir}/workers-narrow-delete-confirmation.png` })
  await page.getByRole("button", { name: "Delete Worker" }).click()
  await expect(page.getByRole("alert")).toContainText("still referenced by durable tasks")
  await page.locator(".worker-table-frame").evaluate((element) => { element.scrollLeft = 0 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)).toBe(false)
  await page.screenshot({ path: `${evidenceDir}/workers-narrow.png` })
  await page.locator(".worker-table-frame").evaluate((element) => { element.scrollLeft = element.scrollWidth / 2 })
  await page.screenshot({ path: `${evidenceDir}/workers-narrow-middle.png` })
  await page.locator(".worker-table-frame").evaluate((element) => { element.scrollLeft = element.scrollWidth })
  await page.screenshot({ path: `${evidenceDir}/workers-narrow-actions.png` })
  expect(api.journal).toContain("create:render-west:8")
  expect(api.journal).toContain("update:d2719a65-16d5-4e97-a756-d8f782769144:v5:6")
  expect(api.journal).toContain("delete:d2719a65-16d5-4e97-a756-d8f782769144:v7")
  expect(api.journal).toContain("settings:v8:uploads5")
  expect(api.journal).toContain("pause")
  expect(api.journal).toContain("resume")
  api.unauthenticateNextMutation()
  await page.getByRole("button", { name: "Enable render-east" }).click()
  await expect(page.getByRole("heading", { name: "Sign in to Controller" })).toBeVisible()
  await page.locator(".login-panel").evaluate(async (element) => {
    await Promise.all(element.getAnimations({ subtree: true }).map((animation) => animation.finished))
  })
  await page.screenshot({ path: `${evidenceDir}/workers-narrow-unauthorized.png` })
  expect(api.journal).toContain("unauthorized:POST:/api/workers/d2719a65-16d5-4e97-a756-d8f782769144/enable")
  await writeFile("../.omo/evidence/videnoa-controller/task-18/workers-settings-errors.txt", [
    "Deterministic Playwright API fixtures were used.",
    "Delete conflict: worker is referenced by tasks -> safe disable guidance rendered.",
    "Rejected deletion restored the invoking row action; successful deletion removed the row and focused Add Worker.",
    "Capacity conflict: worker capacity is below durable usage -> safe capacity guidance rendered.",
    "Duplicate worker name conflict -> adjacent unique name guidance rendered from the production OperationsError shape.",
    "Duplicate API URL conflict -> adjacent unique URL guidance rendered.",
    "Stale worker and settings versions -> one authoritative refetch before retry.",
    "Worker URL, compute slot, settings concurrency bounds, and retry cross-field errors focused and described their first invalid controls.",
    "Offline worker: health probe timed out remained visible independently from enabled policy.",
    "Unauthenticated worker enable mutation -> 401 unauthorized replaced the shell with the captured safe sign-in surface; no credential or request proof was rendered.",
  ].join("\n"), "utf8")
})
